In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data={
    "Name":["akash","Nibir","Payel","Trina","Joya"],
    "Age":[23,25,24,26,22],
    "Score":[89,78,65,50,90]
}
df=pd.DataFrame(data)
df

    Name  Age  Score
0  akash   23     89
1  Nibir   25     78
2  Payel   24     65
3  Trina   26     50
4   Joya   22     90

In [4]:
df.head()

    Name  Age  Score
0  akash   23     89
1  Nibir   25     78
2  Payel   24     65
3  Trina   26     50
4   Joya   22     90

In [5]:
df.tail()

    Name  Age  Score
0  akash   23     89
1  Nibir   25     78
2  Payel   24     65
3  Trina   26     50
4   Joya   22     90

In [7]:
df.shape

(5, 3)

In [12]:
df.columns

Index(['Name', 'Age', 'Score'], dtype='str')

In [13]:
df["Age"]

0    23
1    25
2    24
3    26
4    22
Name: Age, dtype: int64

In [16]:
df["Age"].mean()

np.float64(24.0)

In [17]:
df["Age"].max()

np.int64(26)

In [18]:
df["Age"].min()

np.int64(22)

In [19]:
df[["Name","Score"]]

    Name  Score
0  akash     89
1  Nibir     78
2  Payel     65
3  Trina     50
4   Joya     90

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [21]:
df.describe()

             Age      Score
count   5.000000   5.000000
mean   24.000000  74.400000
std     1.581139  16.979399
min    22.000000  50.000000
25%    23.000000  65.000000
50%    24.000000  78.000000
75%    25.000000  89.000000
max    26.000000  90.000000

Filtering Data

In [22]:
df[df["Score"]>80]

    Name  Age  Score
0  akash   23     89
4   Joya   22     90

In [26]:
df[(df["Score"]>80) & (df["Age"]<24)]

    Name  Age  Score
0  akash   23     89
4   Joya   22     90

In [27]:
df[(df["Score"]>80) | (df["Age"]<24)]

    Name  Age  Score
0  akash   23     89
4   Joya   22     90

Creating a new column

In [29]:
df["Passed"]=df["Score"]>70
df

    Name  Age  Score  Passed
0  akash   23     89    True
1  Nibir   25     78    True
2  Payel   24     65   False
3  Trina   26     50   False
4   Joya   22     90    True

Missing data

In [33]:
data={
    "Name":["Hafiz","Ayman","Nira","Lina","Rony"],
    "Age":[35,np.nan,33,25,23],
    "Score":[60,np.nan,90,np.nan,70]
}
df2=pd.DataFrame(data)
df2

    Name   Age  Score
0  Hafiz  35.0   60.0
1  Ayman   NaN    NaN
2   Nira  33.0   90.0
3   Lina  25.0    NaN
4   Rony  23.0   70.0

In [34]:
df2.isnull()

    Name    Age  Score
0  False  False  False
1  False   True   True
2  False  False  False
3  False  False   True
4  False  False  False

In [35]:
df2.isnull().sum()

Name     0
Age      1
Score    2
dtype: int64